# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  api:
    docker:
      - image: circleci/golang:1.15
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout
      - run: cd api && go mod download
      - run: cd api && go test -v ./...
      - run: cd api && go vet

  frontend:
    docker:
      - image: cimg/python:3.8.0-node
    steps:
      - checkout
      - run: node --version
      - run: cd frontend && yarn
      - run: cd frontend && yarn test
      - run: cd frontend && yarn build


workflows:
  version: 2
  build:
    jobs:
      - api
      - frontend
